spring.application.name=client-service

server.port = 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.docker.compose.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

openapi.service.title=client Service
openapi.service.version=1.0.0
openapi.service.url=http://localhost:8080

springdoc.api-docs.path=/client-service/v3/api-docs
springdoc.swagger-ui.path=/client-service/swagger-ui.html

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.instance.hostname=localhost
